
import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';

Font.register({
  family: 'Helvetica-Bold',
  src: 'https://cdn.jsdelivr.net/npm/helvetica-bold@latest/helvetica-bold.ttf'
});

const styles = StyleSheet.create({
  page: {
    paddingTop: 35,
    paddingBottom: 65,
    paddingHorizontal: 35,
    fontFamily: 'Helvetica',
    fontSize: 10,
    lineHeight: 1.5,
    color: '#333333',
    backgroundColor: '#ffffff',
  },
  header: {
    textAlign: 'center',
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#eeeeee',
    paddingBottom: 10,
  },
  title: {
    fontSize: 22,
    fontFamily: 'Helvetica-Bold',
    color: '#1a2b4d',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 12,
    color: '#555555',
    marginTop: 5,
    textAlign: 'center',
  },
  content: {
    marginTop: 20,
    padding: 15,
    backgroundColor: '#f8f9fa',
    borderRadius: 5,
  },
  contentText: {
    fontFamily: 'Helvetica',
    fontSize: 10,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 35,
    right: 35,
    textAlign: 'center',
    fontSize: 9,
    color: '#999999',
    borderTopWidth: 1,
    borderTopColor: '#eeeeee',
    paddingTop: 10,
  },
});

export const InterviewGuidePDF = ({ title, content }: { title: string; content: string }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header} fixed>
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.subtitle}>Generated by HirePower AI</Text>
      </View>
      
      <View style={styles.content}>
        <Text style={styles.contentText}>{content}</Text>
      </View>
      
      <Text style={styles.footer} fixed>
        Generated on {new Date().toLocaleDateString()} | HirePower AI - Advanced Hiring Solutions
      </Text>
    </Page>
  </Document>
);
