
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Download, Eye, FileText } from "lucide-react";
import { toast } from "sonner";

interface PDFPreviewDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  content: string;
  title: string;
}

export const PDFPreviewDialog = ({ open, onOpenChange, content, title }: PDFPreviewDialogProps) => {
  const generatePDF = () => {
    // Simulate PDF generation
    toast.success("PDF generated successfully!");
    
    // In a real implementation, you would use a library like jsPDF or react-pdf
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl max-h-[80vh]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            PDF Preview
          </DialogTitle>
          <DialogDescription>
            Preview and download your generated interview guide
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <div className="flex justify-between items-center">
            <h3 className="text-lg font-semibold">{title}</h3>
            <div className="flex gap-2">
              <Button variant="outline" size="sm">
                <Eye className="h-4 w-4 mr-2" />
                Preview
              </Button>
              <Button onClick={generatePDF} size="sm">
                <Download className="h-4 w-4 mr-2" />
                Download PDF
              </Button>
            </div>
          </div>

          <Card>
            <CardContent className="p-6">
              <div className="bg-white shadow-lg rounded-lg p-8 max-h-96 overflow-y-auto">
                <div className="text-center mb-6 border-b pb-4">
                  <h1 className="text-2xl font-bold text-slate-800">{title}</h1>
                  <p className="text-slate-600 mt-2">Generated by HirePower AI</p>
                </div>
                
                <div className="prose prose-slate max-w-none">
                  <pre className="whitespace-pre-wrap text-sm leading-relaxed font-sans">
                    {content}
                  </pre>
                </div>
                
                <div className="mt-8 pt-4 border-t text-center text-xs text-slate-500">
                  <p>Generated on {new Date().toLocaleDateString()}</p>
                  <p>HirePower AI - Advanced Hiring Solutions</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <div className="bg-amber-50 p-4 rounded-lg border border-amber-200">
            <p className="text-sm text-amber-800">
              <strong>Note:</strong> This is a preview of your PDF. The actual download will include 
              professional formatting, your company branding, and enhanced styling.
            </p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};
