// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmkqrizerntndxypeftq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impta3FyaXplcm50bmR4eXBlZnRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDI3MDUsImV4cCI6MjA2NTQ3ODcwNX0.jZu7rDPMy6Rct2MzvvZpC_L4H5iUqrZUK0B7HklGQCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);